# PRE-PRECOSSING DATA

---

In [35]:
import pandas as pd
import calendar

In [36]:
import pandas as pd

df1 = pd.read_csv('dataset/dataset.csv')
df2 = pd.read_csv('dataset/dataset2.csv')

df = pd.concat([df1, df2], ignore_index=True)
df

,tj_masuk,tj_keluar,no_rawat,kd_kamar,tgl_masuk,jam_masuk,tgl_keluar,jam_keluar,ttl_biaya,stts_pulang,kelas,trf_kamar,kd_bangsal,nm_bangsal,lama,biaya_sekali,tagihan,png_jawab
0,8/19/2024 22:21,4/8/2025 20:29,2024/08/19/000122,A.13,8/19/2024,22:21:30,4/8/2025,20:29:02,180000,Atas Persetujuan Dokter,Kelas 3,177215,KIIIW,AL-IKHLAS Kelas 3 BPJS,3,0,2422529,BPJS
1,12/28/2024 17:16,1/1/2025 21:17,2024/12/28/000039,1A1,12/28/2024,17:16:26,1/1/2025,21:17:19,450000,Atas Persetujuan Dokter,Kelas 1,281031,UTM1,AL-MAUN Kelas 1 ANAK,5,0,3104658,BPJS KARYAWAN
2,12/30/2024 16:09,1/1/2025 20:40,2024/12/29/000002,III.AN.7,12/30/2024,16:09:25,1/1/2025,20:40:37,120000,Atas Persetujuan Dokter,Kelas 3,177215,ANIII,RUANG ANAK Kelas 3,2,0,2162372,BPJS
3,12/29/2024 20:32,1/1/2025 18:36,2024/12/29/000025,III.AN.2,12/29/2024,20:32:57,1/1/2025,18:36:50,536000,Atas Persetujuan Dokter,Kelas 3,177215,ANIII,RUANG ANAK Kelas 3,4,0,2702204,UMUM
4,12/30/2024 1:44,1/1/2025 11:09,2024/12/29/000039,B.09,12/30/2024,1:44:29,1/1/2025,11:09:26,360000,Membaik,Kelas 3,177215,SOTB,AL-IKHLAS RUANG ISO ( TB ),4,0,2806698,BPJS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7112,2024-12-22 13:20:14,2024-12-24 13:20:14,2024/12/22/000159,N.3,2024-12-22,13:20:14,2024-12-24,13:20:14,4323967,Pulang Paksa,Kelas VIP,209220,KLS3B,NICU TANPA VENTILATOR,1,0,4323967,Jasa Raharja
7113,2024-03-09 11:02:22,2024-03-11 11:02:22,2024/03/09/000009,ICU.4,2024-03-09,11:02:22,2024-03-11,11:02:22,3920492,Membaik,Kelas 2,209220,SOTB,AL-IKHLAS Kelas 3 BPJS,1,0,3920492,BPJS PARTUS
7114,2024-11-17 13:10:56,2024-11-26 13:10:56,2024/11/17/000065,A.09,2024-11-17,13:10:56,2024-11-26,13:10:56,3554478,Sembuh,Kelas VIP,626290,PRN1,PERINATOLOGI,3,0,3554478,Jasa Raharja
7115,2024-04-24 06:38:35,2024-04-29 06:38:35,2024/04/24/000111,III.AN.5,2024-04-24,06:38:35,2024-04-29,06:38:35,4661648,Sehat,Kelas 3,487370,ANII,AR-RAHMAH Kelas 1 Pria,3,0,4661648,BPJS Naik Kelas
7116,2024-04-22 10:48:06,2024-04-27 10:48:06,2024/04/22/000055,B.02,2024-04-22,10:48:06,2024-04-27,10:48:06,2858890,Membaik,Kelas 2,233157,KLS2B,AL-MAUN Kelas VIP,3,0,2858890,BPJS Naik Kelas

In [37]:
kolom_dipakai = [
    'no_rawat',
    'tgl_masuk',
    'tgl_keluar',
    'stts_pulang'
]
df = df[kolom_dipakai]
df

               no_rawat   tgl_masuk  tgl_keluar              stts_pulang
0     2024/08/19/000122   8/19/2024    4/8/2025  Atas Persetujuan Dokter
1     2024/12/28/000039  12/28/2024    1/1/2025  Atas Persetujuan Dokter
2     2024/12/29/000002  12/30/2024    1/1/2025  Atas Persetujuan Dokter
3     2024/12/29/000025  12/29/2024    1/1/2025  Atas Persetujuan Dokter
4     2024/12/29/000039  12/30/2024    1/1/2025                  Membaik
...                 ...         ...         ...                      ...
7112  2024/12/22/000159  2024-12-22  2024-12-24             Pulang Paksa
7113  2024/03/09/000009  2024-03-09  2024-03-11                  Membaik
7114  2024/11/17/000065  2024-11-17  2024-11-26                   Sembuh
7115  2024/04/24/000111  2024-04-24  2024-04-29                    Sehat
7116  2024/04/22/000055  2024-04-22  2024-04-27                  Membaik

[7117 rows x 4 columns]

In [38]:
df['stts_pulang'].unique()

<StringArray>
['Atas Persetujuan Dokter',                 'Membaik',
            'Pindah Kamar',                  'Sembuh',
 'Atas Permintaan Sendiri',               'Meninggal',
                   'Rujuk',                     'APS',
            'Pulang Paksa',               'Lain-lain',
                   'Sehat']
Length: 11, dtype: str

In [39]:
# tambah kolom jumlah tempat tidur
df['jumlah_bed'] = 65
df

,no_rawat,tgl_masuk,tgl_keluar,stts_pulang,jumlah_bed
0,2024/08/19/000122,8/19/2024,4/8/2025,Atas Persetujuan Dokter,65
1,2024/12/28/000039,12/28/2024,1/1/2025,Atas Persetujuan Dokter,65
2,2024/12/29/000002,12/30/2024,1/1/2025,Atas Persetujuan Dokter,65
3,2024/12/29/000025,12/29/2024,1/1/2025,Atas Persetujuan Dokter,65
4,2024/12/29/000039,12/30/2024,1/1/2025,Membaik,65
...,...,...,...,...,...
7112,2024/12/22/000159,2024-12-22,2024-12-24,Pulang Paksa,65
7113,2024/03/09/000009,2024-03-09,2024-03-11,Membaik,65
7114,2024/11/17/000065,2024-11-17,2024-11-26,Sembuh,65
7115,2024/04/24/000111,2024-04-24,2024-04-29,Sehat,65
7116,2024/04/22/000055,2024-04-22,2024-04-27,Membaik,65

In [40]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [no_rawat, tgl_masuk, tgl_keluar, stts_pulang, jumlah_bed]
Index: []

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7117 entries, 0 to 7116
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   no_rawat     7117 non-null   str
 1   tgl_masuk    7117 non-null   str
 2   tgl_keluar   7117 non-null   str
 3   stts_pulang  7117 non-null   str
 4   jumlah_bed   7117 non-null   int64
dtypes: int64(1), str(4)
memory usage: 278.1 KB

In [42]:
df['tgl_masuk'] = pd.to_datetime(df['tgl_masuk'], errors='coerce', format='mixed')
df['tgl_keluar'] = pd.to_datetime(df['tgl_keluar'], errors='coerce', format='mixed')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7117 entries, 0 to 7116
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   no_rawat     7117 non-null   str
 1   tgl_masuk    7116 non-null   datetime64[us]
 2   tgl_keluar   7117 non-null   datetime64[us]
 3   stts_pulang  7117 non-null   str
 4   jumlah_bed   7117 non-null   int64
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 278.1 KB

In [43]:
df['bulan'] = df['tgl_keluar'].dt.month
df['tahun'] = df['tgl_keluar'].dt.year

In [44]:
df['tgl_masuk'] = pd.to_datetime(df['tgl_masuk'])
df['tgl_keluar'] = pd.to_datetime(df['tgl_keluar'])

df['bulan_masuk'] = df['tgl_masuk'].dt.month
df['tahun_masuk'] = df['tgl_masuk'].dt.year

df['bulan_keluar'] = df['tgl_keluar'].dt.month
df['tahun_keluar'] = df['tgl_keluar'].dt.year

In [45]:
df_masuk = df.groupby(['bulan_masuk', 'tahun_masuk']).agg(
    pasien_masuk=('no_rawat', 'nunique')
).reset_index()

In [46]:
df_keluar = df.groupby(['bulan_keluar', 'tahun_keluar']).agg(
    pasien_keluar=('no_rawat', 'nunique'),
    pasien_meninggal=('stts_pulang', lambda x: (x.str.lower() == 'meninggal').sum()),
    total_hari_perawatan=(
        'tgl_keluar',
        lambda x: (x - df.loc[x.index, 'tgl_masuk']).dt.days.sum()
    ),
    tempat_tidur=('jumlah_bed', 'first')
).reset_index()

penggabungan data dilakukan menggunakan operasi merge berdasarkan kesamaan bulan dan tahun

In [47]:
df_rekap = pd.merge(
    df_keluar,
    df_masuk,
    left_on=['bulan_keluar', 'tahun_keluar'],
    right_on=['bulan_masuk', 'tahun_masuk'],
    how='left'
)

In [48]:
df_rekap = df_rekap.rename(columns={
    'bulan_keluar': 'bulan',
    'tahun_keluar': 'tahun'
})

df_rekap = df_rekap[
    ['bulan', 'tahun', 'pasien_masuk', 'pasien_keluar',
     'pasien_meninggal', 'total_hari_perawatan', 'tempat_tidur']
]

Nilai periode_bulan dihitung sebagai jumlah hari aktual pada setiap bulan berdasarkan tahun

In [49]:
df_rekap['periode_bulan'] = df_rekap.apply(
    lambda x: calendar.monthrange(int(x['tahun']), int(x['bulan']))[1],
    axis=1
)

In [50]:
df_rekap['BOR'] = (
    df_rekap['total_hari_perawatan'] /
    (df_rekap['tempat_tidur'] * df_rekap['periode_bulan'])
) * 100

In [51]:
df_rekap['LOS'] = (
    df_rekap['total_hari_perawatan'] /
    df_rekap['pasien_keluar']
)

In [52]:
df_rekap['GDR'] = (
    df_rekap['pasien_meninggal'] /
    df_rekap['pasien_keluar']
) * 1000

In [53]:
df_rekap = df_rekap.sort_values(by=['tahun', 'bulan']).reset_index(drop=True)
df_rekap

,bulan,tahun,pasien_masuk,pasien_keluar,pasien_meninggal,total_hari_perawatan,tempat_tidur,periode_bulan,BOR,LOS,GDR
0,1,2024,244,231,1,1262.0,65,31,62.630273,5.463203,4.329004
1,2,2024,252,244,7,1317.0,65,29,69.867374,5.397541,28.688525
2,3,2024,263,274,6,1523.0,65,31,75.583127,5.558394,21.897810
3,4,2024,240,246,4,1337.0,65,30,68.564103,5.434959,16.260163
4,5,2024,205,216,4,1176.0,65,31,58.362283,5.444444,18.518519
5,6,2024,237,221,7,1193.0,65,30,61.179487,5.398190,31.674208
6,7,2024,220,224,1,1219.0,65,31,60.496278,5.441964,4.464286
7,8,2024,236,242,6,1277.0,65,31,63.374690,5.276860,24.793388
8,9,2024,223,221,2,1203.0,65,30,61.692308,5.443439,9.049774
9,10,2024,236,232,1,1313.0,65,31,65.161290,5.659483,4.310345
10,11,2024,224,228,5,1258.0,65,30,64.512821,5.517544,21.929825
11,12,2024,204,214,8,1098.0,65,31,54.491315,5.130841,37.383178
12,1,2025,297,287,1,698.0,65,31,34.640199,2.432056,3.484321
13,2,2025,249,254,3,586.0,65,28,32.197802,2.307087,11.811024
14,3,2025,252,258,4,561.0,65,31,27.841191,2.174419,15.503876
15,4,2025,280,268,4,833.0,65,30,42.717949,3.108209,14.925373
16,5,2025,258,263,3,589.0,65,31,29.230769,2.239544,11.406844
17,6,2025,250,247,1,587.0,65,30,30.102564,2.376518,4.048583
18,7,2025,315,317,4,773.0,65,31,38.362283,2.438486,12.618297
19,8,2025,293,297,5,695.0,65,31,34.491315,2.340067,16.835017
20,9,2025,322,310,4,791.0,65,30,40.564103,2.551613,12.903226
21,10,2025,366,370,3,882.0,65,31,43.771712,2.383784,8.108108
22,11,2025,306,317,7,744.0,65,30,38.153846,2.347003,22.082019
23,12,2025,234,250,3,612.0,65,31,30.372208,2.448000,12.000000

In [54]:
df_indikator = df_rekap[['bulan', 'tahun', 'BOR', 'LOS', 'GDR']]
df_indikator

    bulan  tahun        BOR       LOS        GDR
0       1   2024  62.630273  5.463203   4.329004
1       2   2024  69.867374  5.397541  28.688525
2       3   2024  75.583127  5.558394  21.897810
3       4   2024  68.564103  5.434959  16.260163
4       5   2024  58.362283  5.444444  18.518519
5       6   2024  61.179487  5.398190  31.674208
6       7   2024  60.496278  5.441964   4.464286
7       8   2024  63.374690  5.276860  24.793388
8       9   2024  61.692308  5.443439   9.049774
9      10   2024  65.161290  5.659483   4.310345
10     11   2024  64.512821  5.517544  21.929825
11     12   2024  54.491315  5.130841  37.383178
12      1   2025  34.640199  2.432056   3.484321
13      2   2025  32.197802  2.307087  11.811024
14      3   2025  27.841191  2.174419  15.503876
15      4   2025  42.717949  3.108209  14.925373
16      5   2025  29.230769  2.239544  11.406844
17      6   2025  30.102564  2.376518   4.048583
18      7   2025  38.362283  2.438486  12.618297
19      8   2025  34.491315  2.340067  16.835017
20      9   2025  40.564103  2.551613  12.903226
21     10   2025  43.771712  2.383784   8.108108
22     11   2025  38.153846  2.347003  22.082019
23     12   2025  30.372208  2.448000  12.000000

rata2

In [55]:
rata_bor = df_rekap['BOR'].mean()
rata_los = df_rekap['LOS'].mean()

In [56]:
gdr_tahunan = (
    df_rekap['pasien_meninggal'].sum() /
    df_rekap['pasien_keluar'].sum()
) * 1000

In [57]:
df_ringkas_tahun = pd.DataFrame({
    'tahun': [2025],
    'BOR_rata_rata': [round(rata_bor, 2)],
    'LOS_rata_rata': [round(rata_los, 2)],
    'GDR_tahunan_per_1000': [round(gdr_tahunan, 2)]
})

df_ringkas_tahun

   tahun  BOR_rata_rata  LOS_rata_rata  GDR_tahunan_per_1000
0   2025          49.52           3.93                 15.09

# label

In [58]:
df_manajemen = pd.read_csv("dataset/Salin dari tabel_langkah_manajemen.csv")
df_rekomendasi = pd.read_csv("dataset/tabel_jenis_rekomendasi.csv")

In [59]:
df_manajemen

,bulan,tahun,Kerja Sama,Triase IGD,Sistem Rujukan,Alat Medis,Pelatihan Dokter,Kualifikasi Staf,Pelayanan Pasien
0,1,2024,-,-,-,-,-,✓,✓
1,2,2024,-,✓,✓,-,✓,-,-
2,3,2024,-,✓,✓,-,✓,-,-
3,4,2024,-,-,-,-,-,✓,✓
4,5,2024,✓,-,-,-,-,-,✓
5,6,2024,-,✓,-,-,✓,✓,-
6,7,2024,-,-,-,-,-,✓,✓
7,8,2024,-,-,-,-,-,✓,✓
8,9,2024,-,-,-,-,-,✓,✓
9,10,2024,-,✓,✓,-,✓,-,-
10,11,2024,-,✓,✓,✓,-,-,-
11,12,2024,-,✓,-,-,✓,-,✓
12,1,2025,✓,-,✓,-,-,-,-
13,2,2025,✓,-,✓,-,-,-,✓
14,3,2025,✓,-,✓,-,-,-,✓
15,4,2025,✓,-,-,-,✓,✓,-
16,5,2025,✓,-,-,-,-,-,✓
17,6,2025,✓,-,-,-,-,-,✓
18,7,2025,-,-,-,-,✓,✓,✓
19,8,2025,-,-,-,-,✓,✓,✓
20,9,2025,-,-,-,-,✓,✓,✓
21,10,2025,-,-,✓,-,-,-,✓
22,11,2025,-,-,✓,✓,-,-,✓
23,12,2025,-,✓,✓,✓,-,-,-

In [60]:
kolom_tindakan = df_manajemen.columns[2:]

for col in kolom_tindakan:
    df_manajemen[col] = df_manajemen[col].map(
        lambda x: True if str(x).strip() == '✓' else False
    )

In [61]:
df_manajemen

,bulan,tahun,Kerja Sama,Triase IGD,Sistem Rujukan,Alat Medis,Pelatihan Dokter,Kualifikasi Staf,Pelayanan Pasien
0,1,2024,False,False,False,False,False,True,True
1,2,2024,False,True,True,False,True,False,False
2,3,2024,False,True,True,False,True,False,False
3,4,2024,False,False,False,False,False,True,True
4,5,2024,True,False,False,False,False,False,True
5,6,2024,False,True,False,False,True,True,False
6,7,2024,False,False,False,False,False,True,True
7,8,2024,False,False,False,False,False,True,True
8,9,2024,False,False,False,False,False,True,True
9,10,2024,False,True,True,False,True,False,False
10,11,2024,False,True,True,True,False,False,False
11,12,2024,False,True,False,False,True,False,True
12,1,2025,True,False,True,False,False,False,False
13,2,2025,True,False,True,False,False,False,True
14,3,2025,True,False,True,False,False,False,True
15,4,2025,True,False,False,False,True,True,False
16,5,2025,True,False,False,False,False,False,True
17,6,2025,True,False,False,False,False,False,True
18,7,2025,False,False,False,False,True,True,True
19,8,2025,False,False,False,False,True,True,True
20,9,2025,False,False,False,False,True,True,True
21,10,2025,False,False,True,False,False,False,True
22,11,2025,False,False,True,True,False,False,True
23,12,2025,False,True,True,True,False,False,False

In [62]:
print(df_indikator.columns)
print(df_manajemen.columns)

Index(['bulan', 'tahun', 'BOR', 'LOS', 'GDR'], dtype='str')
Index(['bulan', 'tahun', 'Kerja Sama', 'Triase IGD', 'Sistem Rujukan',
       'Alat Medis', 'Pelatihan Dokter', 'Kualifikasi Staf',
       'Pelayanan Pasien'],
      dtype='str')

In [63]:
df_indikator[['bulan','tahun']].duplicated().sum()
df_manajemen[['bulan','tahun']].duplicated().sum()

np.int64(0)

In [64]:
print(len(df_indikator))
print(len(df_manajemen))

24
24

In [65]:
df_merge = pd.merge(
    df_indikator,
    df_manajemen,
    on=['bulan', 'tahun'], 
    how='left',
    validate='one_to_one'
)

In [66]:
len(df_merge.columns)

12

In [67]:
df_merge.columns

Index(['bulan', 'tahun', 'BOR', 'LOS', 'GDR', 'Kerja Sama', 'Triase IGD',
       'Sistem Rujukan', 'Alat Medis', 'Pelatihan Dokter', 'Kualifikasi Staf',
       'Pelayanan Pasien'],
      dtype='str')

In [68]:
df_merge.columns = [
    'bulan',
    'tahun',
    'BOR',
    'LOS',
    'GDR',
    'Bulan_Tahun',
    'Kerja Sama',
    'Triase IGD',
    'Sistem Rujukan',
    'Alat Medis',
    'Pelatihan Dokter',
    'Kualifikasi Staf',
    'Pelayanan Pasien'
]

ValueError: Length mismatch: Expected axis has 12 elements, new values have 13 elements

In [ ]:
kolom_tindakan = [
    'Kerja Sama',
    'Triase IGD',
    'Sistem Rujukan',
    'Alat Medis',
    'Pelatihan Dokter',
    'Kualifikasi Staf',
    'Pelayanan Pasien'
]

df_merge[kolom_tindakan] = df_merge[kolom_tindakan].astype(bool)

In [71]:
df_rekap

,bulan,tahun,pasien_masuk,pasien_keluar,pasien_meninggal,total_hari_perawatan,tempat_tidur,periode_bulan,BOR,LOS,GDR
0,1,2024,244,231,1,1262.0,65,31,62.630273,5.463203,4.329004
1,2,2024,252,244,7,1317.0,65,29,69.867374,5.397541,28.688525
2,3,2024,263,274,6,1523.0,65,31,75.583127,5.558394,21.897810
3,4,2024,240,246,4,1337.0,65,30,68.564103,5.434959,16.260163
4,5,2024,205,216,4,1176.0,65,31,58.362283,5.444444,18.518519
5,6,2024,237,221,7,1193.0,65,30,61.179487,5.398190,31.674208
6,7,2024,220,224,1,1219.0,65,31,60.496278,5.441964,4.464286
7,8,2024,236,242,6,1277.0,65,31,63.374690,5.276860,24.793388
8,9,2024,223,221,2,1203.0,65,30,61.692308,5.443439,9.049774
9,10,2024,236,232,1,1313.0,65,31,65.161290,5.659483,4.310345
10,11,2024,224,228,5,1258.0,65,30,64.512821,5.517544,21.929825
11,12,2024,204,214,8,1098.0,65,31,54.491315,5.130841,37.383178
12,1,2025,297,287,1,698.0,65,31,34.640199,2.432056,3.484321
13,2,2025,249,254,3,586.0,65,28,32.197802,2.307087,11.811024
14,3,2025,252,258,4,561.0,65,31,27.841191,2.174419,15.503876
15,4,2025,280,268,4,833.0,65,30,42.717949,3.108209,14.925373
16,5,2025,258,263,3,589.0,65,31,29.230769,2.239544,11.406844
17,6,2025,250,247,1,587.0,65,30,30.102564,2.376518,4.048583
18,7,2025,315,317,4,773.0,65,31,38.362283,2.438486,12.618297
19,8,2025,293,297,5,695.0,65,31,34.491315,2.340067,16.835017
20,9,2025,322,310,4,791.0,65,30,40.564103,2.551613,12.903226
21,10,2025,366,370,3,882.0,65,31,43.771712,2.383784,8.108108
22,11,2025,306,317,7,744.0,65,30,38.153846,2.347003,22.082019
23,12,2025,234,250,3,612.0,65,31,30.372208,2.448000,12.000000

In [72]:
df_rekap.to_csv('df_rekap.csv', index=False)

# CBR

In [73]:
fitur = ['BOR', 'LOS', 'GDR']

In [74]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_scaled = df_rekap.copy()

df_scaled[fitur] = scaler.fit_transform(df_rekap[fitur])

In [75]:
import numpy as np

def euclidean_distance(case1, case2):
    return np.sqrt(np.sum((case1 - case2)**2))

In [76]:
# contoh kasus baru
kasus_baru = np.array([[0.60, 0.50, 0.30]])  # nanti pakai scaler juga

kasus_baru_scaled = scaler.transform([[60, 4.5, 10]])

d:\Project\Python\projekta\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

In [77]:
distances = []

for i in range(len(df_scaled)):
    case_lama = df_scaled.loc[i, fitur].values
    jarak = euclidean_distance(kasus_baru_scaled[0], case_lama)
    distances.append(jarak)

df_scaled['Distance'] = distances

In [78]:
hasil = df_scaled.sort_values('Distance').iloc[0]
hasil

bulan                      9.000000
tahun                   2024.000000
pasien_masuk             223.000000
pasien_keluar            221.000000
pasien_meninggal           2.000000
total_hari_perawatan    1203.000000
tempat_tidur              65.000000
periode_bulan             30.000000
BOR                        0.709044
LOS                        0.938009
GDR                        0.164178
Distance                   0.274455
Name: 8, dtype: float64

DATASET

In [69]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in .\.venv\Lib\site-packages (1.1.2)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.47-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.47-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 2.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.1 MB 2.0 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 2.0 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.8 MB/s  0:00:01
Downloading greenlet-3.3.2-cp314-cp314-win_amd64.whl (232 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.3.2 sqlalchemy-2.0.47 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

In [79]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:@localhost:3306/rekom"
)

engine.connect()

In [80]:
df_kasus = df_rekap[['bulan', 'tahun', 'BOR', 'LOS', 'GDR']].copy()

df_kasus.columns = ['bulan', 'tahun', 'bor', 'los', 'gdr']

In [81]:
df_kasus.head()

   bulan  tahun        bor       los        gdr
0      1   2024  62.630273  5.463203   4.329004
1      2   2024  69.867374  5.397541  28.688525
2      3   2024  75.583127  5.558394  21.897810
3      4   2024  68.564103  5.434959  16.260163
4      5   2024  58.362283  5.444444  18.518519

In [82]:
df_kasus.to_sql(
    'kasus',
    engine,
    if_exists='append',
    index=False
)

24